DB_ORACLE_HOST: localhost
DB_ORACLE_PORT: 1521
DB_ORACLE_SID: XE
DB_ORACLE_USER: ermmonk
DB_ORACLE_PASSWORD: ermmonk

#config server
#server:
#    port: ${SERVER_PORT}

#config database connection
spring:
    application:
        name: erm_monk
    datasource:
        platform: oracle
        url: jdbc:oracle:thin:@${DB_ORACLE_HOST}:${DB_ORACLE_PORT}/${DB_ORACLE_SID}
        username: ${DB_ORACLE_USER}
        password: ${DB_ORACLE_PASSWORD}
        driver-class-name: oracle.jdbc.driver.OracleDriver
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.OracleDialect
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Bangkok

#config logger
logging:
    level:
        root: INFO
        org:
            hibernate:
                SQL: DEBUG
        th:
            go:
                nhso:
                    erm: DEBUG